service: email-sender

provider:
  name: aws
  runtime: python3.8
  region: ap-south-1

functions:
  app:
    handler: wsgi_handler.lambda_handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

package:
  exclude:
    - node_modules/**
    - .git/**
    - .gitignore

custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements

# Define environment variables here
# environment:
#   VAR_NAME: value
